# Site settings
title: Tickleworks
description: > # this means to ignore newlines until "baseurl:"
  A blog about everything game programming related: AI, rendering,
  realtime networking, engine architecture, math, physics, etc.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.tickleworks.dk" # the base hostname & protocol for your site
github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: rouge
