# Site settings
title: Bonsai7
description: >
  A blog about everything game programming related: AI, rendering,
  realtime networking, engine architecture, math, physics, etc.
url: "http://www.bonsai7.dk" # the base hostname & protocol for your site
permalink: /:title.html

# Build settings
markdown: kramdown
highlighter: pygments
